on:
  push:
    branches:
      - master













jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name:  'printing folder '
        run: ls

      - name:   'test print'
        run: echo Esraa 