on:
  push:
    branches:
     - master













jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      -name: "TEST"
       run: pwd

       -name: "TEST printing   "
       run: echo Esraa