on:
  push:
    branches:
      - master













jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name:  'Before '
        run: ls

      - name:   'test print'
        run: echo Esraa 

      - uses: actions/checkout@v3
      - name:   'After'
        run: ls   