on:
  push:
    branches:
      - master













jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: "login to Docker hub"
        run: docker login --username esraa44 --password dckr_pat_WsdWRqYkfncCQ44N6_8_aMgqHfc

      - name: "Bulding docker image "
        run: docker build -t esraa44/myimage .

      - name: "pushing to Docker hub "
        run: docker push esraa44/myimage 